version: '3.8'

services:
  app:
    image: anonyymi/miniboard:latest
    pull_policy: build
    build:
      context: .
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-fs', 'http://localhost:80']
      interval: 5s
      timeout: 1s
      retries: 2
      start_period: 10s
    networks:
      - app
    volumes:
      - ./public:/app/public:Z
      - app:/app/public/src
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - mariadb

  test:
    image: anonyymi/miniboard:latest
    pull_policy: never
    restart: on-failure
    command: ['bash', '-c', 'XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text --coverage-clover coverage.xml --coverage-html ./coverage']
    networks:
      - test
    volumes:
      - ./tests/unit:/app/tests/unit:Z

  mariadb:
    image: mariadb:10.6
    restart: always
    networks:
      - app
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      MYSQL_CHARSET: 'utf8'
      MYSQL_COLLATION: 'utf8mb4_unicode_ci'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'miniboard'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    networks:
      - app
    ports:
      - 127.0.0.1:8080:80
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=admin
      - PMA_PASSWORD=admin

  flyway:
    image: flyway/flyway:latest-alpine
    restart: on-failure
    networks:
      - app
    volumes:
      - ./migrations:/flyway/sql:Z
    command: -url=jdbc:mysql://mariadb -schemas=miniboard -user=root -password=root -connectRetries=60 migrate
    depends_on:
      - mariadb

networks:
  app:
    driver: bridge
  test:
    driver: bridge

volumes:
  app:
  mariadb:
