version: '3.8'

services:
  app:
    image: ghcr.io/anonyymi/miniboard/app:latest
    deploy:
      replicas: 3
    restart: on-failure
    networks:
      - app
    volumes:
      - app:/app/public/src
    expose:
      - 9000
    environment:
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE}
      MB_TIMEZONE: Europe/Helsinki
      MB_DB_HOST: mariadb
      MB_DB_NAME: ${DB_NAME}
      MB_DB_USER: ${DB_USER}
      MB_DB_PASS: ${DB_PASS}
      REDIS_HOST: redis
      REDIS_PASS: ${REDIS_PASS}
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.6
    restart: on-failure
    healthcheck:
      test: ['CMD', 'mysqladmin', '-u${DB_USER}', '-p${DB_PASS}', 'ping', '--silent']
      interval: 5s
      timeout: 1s
      retries: 2
      start_period: 10s
    networks:
      - app
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - 3306
    environment:
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8mb4_unicode_ci
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

  flyway:
    image: ghcr.io/anonyymi/miniboard/flyway:latest
    restart: on-failure
    networks:
      - app
    command: -url=jdbc:mysql://mariadb -schemas=${DB_NAME} -user=root -password=${DB_ROOT_PASS} -connectRetries=60 migrate
    depends_on:
      - mariadb

  redis:
    image: redis:7.0-alpine
    restart: on-failure
    command: '--save 60 1 --loglevel warning --requirepass ${REDIS_PASS}'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 1s
      retries: 2
      start_period: 10s
    networks:
      - app
    volumes:
      - redis:/data
    expose:
      - 6379

  nginx:
    image: ghcr.io/anonyymi/miniboard/nginx:latest
    restart: on-failure
    networks:
      - app
    volumes:
      - app:/app/public/src:ro
    ports:
      - '80:80'
      - '443:443'
    environment:
      NGINX_CLIENT_MAX_BODY_SIZE: ${NGINX_CLIENT_MAX_BODY_SIZE}
      NGINX_REAL_IP_HEADER: ${NGINX_REAL_IP_HEADER}
      NGINX_REAL_IP_VAR: ${NGINX_REAL_IP_VAR}
      APP_HOST: app
      APP_PORT: 9000
    depends_on:
      - app

  csam-scanner:
    image: ghcr.io/anonyymi/miniboard/csam-scanner:latest
    deploy:
      replicas: 1
    restart: on-failure
    networks:
      - app
    expose:
      - 8000
    environment:
      DB_HOST: mariadb
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      ORIGINATOR: miniboard
      TOLERANCE: 0.95
    depends_on:
      - mariadb

networks:
  app:
    driver: bridge

volumes:
  app:
  mariadb:
  redis:
