apiVersion: v1
kind: Service
metadata:
  name: miniboard-mariadb
  labels:
    run: miniboard-mariadb
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    run: miniboard-mariadb

---
apiVersion: v1
kind: Service
metadata:
  name: miniboard-app
  labels:
    run: miniboard-app
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: fpm
  selector:
    run: miniboard-app

---
apiVersion: v1
kind: Service
metadata:
  name: miniboard-nginx
  labels:
    run: miniboard-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    run: miniboard-nginx
