apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniboard-app
spec: # spec for deployment
  selector:
    matchLabels:
      run: miniboard-app
  replicas: 3
  template: # blueprint for pods
    metadata:
      labels:
        run: miniboard-app # service looks for this label
    spec: # spec for pods
      containers:
      - name: miniboard-app
        image: ghcr.io/anonyymi/miniboard/app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            memory: 1024Mi
        env:
        - name: PHP_POST_MAX_SIZE
          value: 100M
        - name: PHP_UPLOAD_MAX_FILESIZE
          value: 128M
        - name: MB_TIMEZONE
          value: Europe/Helsinki
        - name: MB_DB_HOST
          value: miniboard-mariadb
        - name: MB_DB_NAME
          value: miniboard_db
        - name: MB_DB_USER
          valueFrom:
            secretKeyRef:
              name: miniboard-mariadb-user
              key: USER
        - name: MB_DB_PASS
          valueFrom:
            secretKeyRef:
              name: miniboard-mariadb-user
              key: PASSWORD
        - name: REDIS_HOST
          value: miniboard-redis
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: miniboard-redis-auth
              key: PASSWORD
        volumeMounts:
        - name: miniboard-app-pv
          mountPath: /app/public/src
      volumes:
      - name: miniboard-app-pv
        persistentVolumeClaim:
          claimName: miniboard-app-pv-claim

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniboard-nginx
spec:
  selector:
    matchLabels:
      run: miniboard-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: miniboard-nginx
    spec:
      containers:
      - name: miniboard-nginx
        image: ghcr.io/anonyymi/miniboard/nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            memory: 256Mi
        env:
        - name: NGINX_CLIENT_MAX_BODY_SIZE
          value: 32M
        - name: NGINX_REAL_IP_HEADER
          value: X-Forwarded-For
        - name: NGINX_REAL_IP_VAR
          value: $http_x_forwarded_for
        - name: APP_HOST
          value: miniboard-app
        - name: APP_PORT
          value: '9000'
        volumeMounts:
        - name: miniboard-nginx-pv
          mountPath: /app/public/src
          readOnly: true
      volumes:
      - name: miniboard-nginx-pv
        persistentVolumeClaim:
          claimName: miniboard-app-pv-claim
          readOnly: true
