apiVersion: v1
kind: Pod
metadata:
  name: pod-miniboard-flyway
spec: # spec for pod
  containers:
  - name: miniboard-flyway
    image: ghcr.io/anonyymi/miniboard/flyway:latest
    args: ["-url=jdbc:mysql://miniboard-mariadb", "-schemas=$(DB_NAME)", "-user=root", "-password=$(DB_ROOT_PASS)", "-connectRetries=60", "migrate"]
    env:
    - name: DB_NAME
      value: miniboard_db
    - name: DB_ROOT_PASS
      valueFrom:
        secretKeyRef:
          name: miniboard-mariadb-root
          key: PASSWORD
  restartPolicy: OnFailure
