apiVersion: v1
kind: Secret
metadata:
  name: miniboard-mariadb-root
type: Opaque
stringData:
  PASSWORD: "root"

---
apiVersion: v1
kind: Secret
metadata:
  name: miniboard-mariadb-user
type: Opaque
stringData:
  USER: "miniboard_db_user"
  PASSWORD: "miniboard_db_pass"

---
apiVersion: v1
kind: Secret
metadata:
  name: miniboard-redis-auth
type: Opaque
stringData:
  PASSWORD: "miniboard_redis_pass"
