apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniboard-app-pv-claim
  labels:
    run: miniboard-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1024M
