apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniboard-mariadb-pv-claim
  labels:
    run: miniboard-mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512M

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniboard-redis-pv-claim
  labels:
    run: miniboard-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256M

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniboard-app-pv-claim
  labels:
    run: miniboard-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1024M
