name: Run build

on:
  push:
    branches:
      - 'master'

env:
  REPO: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - id: meta
      #   uses: docker/metadata-action@4
      #   with:
      #     images: |
      #       ghcr.io/anonyymi/miniboard/app
      #       ghcr.io/anonyymi/miniboard/flyway
      #       ghcr.io/anonyymi/miniboard/nginx
      - uses: docker/bake-action@master
        with:
          push: false
          load: true
          set: |
            app.cache-from=type=gha
            app.cache-to=type=gha
      - name: Build
        run: docker compose -f docker-compose.prod.yml build
      - name: Push
        run: |
          docker image ls
          docker push ghcr.io/anonyymi/miniboard/app:latest
          docker push ghcr.io/anonyymi/miniboard/flyway:latest
          docker push ghcr.io/anonyymi/miniboard/nginx:latest
