name: Run build

on:
  push:
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REPO: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get short SHA
        run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Set version stub
        run: |
          sed -i "s/_MB_VERSION_STUB_/${SHORT_SHA}/g" public/version.php
          cat public/version.php

      - name: Build & push (app)
        run: |
          docker buildx build \
            -t ghcr.io/anonyymi/miniboard/app:latest \
            -t ghcr.io/anonyymi/miniboard/app:${SHORT_SHA} \
            -f docker/miniboard/Dockerfile.prod \
            --platform=linux/arm64,linux/amd64 \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --push .

      - name: Build & push (nginx)
        run: |
          docker buildx build \
            -t ghcr.io/anonyymi/miniboard/nginx:latest \
            -t ghcr.io/anonyymi/miniboard/nginx:${SHORT_SHA} \
            -f docker/nginx/Dockerfile \
            --platform=linux/arm64,linux/amd64 \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --push .

      - name: Build & push (flyway)
        run: |
          docker buildx build \
            -t ghcr.io/anonyymi/miniboard/flyway:latest \
            -t ghcr.io/anonyymi/miniboard/nginx:${SHORT_SHA} \
            -f docker/flyway/Dockerfile \
            --platform=linux/arm64,linux/amd64 \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --push .
