name: Run tests

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/bake-action@master
        with:
          push: false
          load: true
          set: |
            app.cache-from=type=gha
            app.cache-to=type=gha
      - name: Test
        run: docker-compose run --name 'miniboard_test_${{ github.sha }}' test
      - name: Copy
        run: docker cp 'miniboard_test_${{ github.sha }}':/app/coverage.xml ./
      - name: Coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          format: markdown
          output: both
      - name: Report
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
