name: Run build

on:
  push:
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REPO: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        image:
          - name: app
            folder: docker/miniboard
            dockerfile: Dockerfile.prod
          - name: nginx
            folder: docker/nginx
            dockerfile: Dockerfile
          - name: flyway
            folder: docker/flyway
            dockerfile: Dockerfile
          - name: csam-scanner
            folder: docker/csam-scanner
            dockerfile: Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get short SHA
        run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Set version stub
        run: |
          sed -i "s/_MB_VERSION_STUB_/${SHORT_SHA}/g" public/version.php
          cat public/version.php
      - name: Build & push ${{ matrix.image.name }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.image.folder }}/${{ matrix.image.dockerfile }}
          push: true
          tags: |
            ghcr.io/minilauta/miniboard/${{ matrix.image.name }}:latest
            ghcr.io/minilauta/miniboard/${{ matrix.image.name }}:${{ env.SHORT_SHA }}
          platforms: |
            linux/arm64
            linux/amd64
          cache-from: type=gha,scope=${{ github.ref_name }}-build-${{ matrix.image.name }}
          cache-to: type=gha,scope=${{ github.ref_name }}-build-${{ matrix.image.name }},mode=max
