name: Run tests

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/bake-action@master
        with:
          push: false
          load: true
          set: |
            test.cache-from=type=gha
            test.cache-to=type=gha
      - name: Build
        run: docker-compose build
      - name: Test
        run: docker-compose run test
